blueprint:
  name: Motion-activated Action
  description: Fire action when motion is detected.
  domain: automation
  author: Custom Blueprint
  input:
    motion_entity:
      name: Motion Sensor
      description: The motion or occupancy sensor that will trigger the action.
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    action_on_motion:
      name: Action motion detected
      description: The action(s) to execute when motion is detected.
      selector:
        action: {}
    action_off_motion:
      name: Action motion off
      description: The action(s) to execute when there is no motion.
      selector:
        action: {}
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

actions:
  - alias: "Fire on-motion action"
    choose: []
    default: !input action_on_motion
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      trigger: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Fire off-motion action"
    choose: []
    default: !input action_off_motion